services:
  api-launching:
    image: img-launch
    container_name: api-launching
    build:
      context: ../..
      dockerfile: docker/api-launching/Dockerfile
    ports:
      - "5211:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_ENVIRONMENT=Production
    networks:
      - challenge-net

networks:
  challenge-net:
    external: true