services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sql-postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mouse123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - challenge-net

volumes:
  postgres_data:
    driver: local

networks:
  challenge-net:
    external: true