services:
  api-gateway:
    image: img-gw
    container_name: api-gateway
    build:
      context: ../..
      dockerfile: docker/api-gateway/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_ENVIRONMENT=Production
    networks:
      - challenge-net

networks:
  challenge-net:
    external: true
