@Challenge.SolutionArchitecture.LaunchingService_HostAddress = http://localhost:5211

GET {{Challenge.SolutionArchitecture.LaunchingService_HostAddress}}/weatherforecast/
Accept: application/json

###
